### ISSUE TITLE
DBMon perf testing

### ISSUE THREAD

**Issue by davistan** [magnumjs/mag.js#13]
Hi, nice work on this library!

Just a suggestion to also add in a PR for your library on the following page - https://github.com/mathieuancelin/js-repaint-perfs/

**Comment by magnumjs** [comment]
Hi there, thanks for the great suggestion, I will definitely check it out!

**Comment by magnumjs** [comment]
I submitted a pull request. https://github.com/mathieuancelin/js-repaint-perfs/pull/25

**Comment by davistan** [comment]
That’s great. Thanks.
